name: sitemark
description: 添加书签
title: "[SiteMark] 添加书签"
labels: ["未分类"]
body:
- type: input
  attributes:
    label: 网站名称
    description: 输入网站的名称
    placeholder: ex. Github 
  validations:
    required: true
- type: input
  attributes:
    label: 网站 URL
    description: 输入网站 URL
    placeholder: ex. https://github.com
  validations:
    required: true
